version: '3.8'

services:
  # Backend Development Service (NestJS with hot reload)
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    container_name: demo-backend-dev
    ports:
      - "3001:3001"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - app-network
    restart: unless-stopped
    command: npm run start:dev

  # Frontend Development Service (Next.js with hot reload)
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: deps
    container_name: demo-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

networks:
  app-network:
    driver: bridge
    name: demo-app-network 